### ISSUE TITLE
fine grid + ghost cell + t(n + .5) interpolation ? 

### ISSUE THREAD

**Issue by rochekj** [amath574w2015/am574-group03#3]
Hi Randy, Saumya and I have made good progress but are somewhat stumped on an issue regarding the interpolation of the fine grid t(n+1/2) values.

Please reference figure 2.1 from the paper for this question. 
To get qhat_{m+1}^1 do you use bilinear interpolation with coarse cell values (q_{j-1}^{0},q_{j}^{0},q_{j-1}^{1},q_{j}^{1})? Or do you estimate hatted values at t(n+1) in the ghost cell and use the hatted values at 0, and 1, and the q values at 0, 1 for a bilinear interpolation with the same cell? 

Or, please advise.

**Comment by rjleveque** [comment]
I think the way it's done in 2d is as you first describe: use bilinear interpolation with coarse cell values (q_{j-1}^{0},q_{j}^{0},q_{j-1}^{1},q_{j}^{1}) to interpolate to any ghost cells that falls in the rectangle bounded by these 4 cell centers, i.e. qhat_{m+1}^n for n=0,1.  

The second row of ghost cells for this case (refinement by 2), qhat_{m+2}^n, should probably come from bilinear interpolation between q_j^0, q_j^1, q_{j+1}^0, and q_{j+1}^1.  If refinement was by 4 instead of two, both ghost cells would lie to the left of the q_j points and the first bilinear interpolant could be used for all ghost cells.

**Comment by rochekj** [comment]
makes sense, thank you.
